// Globally shared history store
export let EVENTS_STORE = [
  {
    id: '1',
    type: '103',
    title: '103 Təcili Tibbi Yardım',
    status: 'Briqada Yoldadır',
    statusType: 'red',
    date: '30 İyun 2026, 11:15',
    address: 'Bakı, Nizami küçəsi 45',
    attachments: [
      { type: 'audio', label: '15s Səs Yazısı Arxivləndi', icon: 'waveform', color: '#E11D48' },
      { type: 'image', label: 'Hadisə Anı Fotosu Arxivləndi', icon: 'image-outline', color: '#2563EB' },
    ],
    bgColor: '#FFF1F1',
    borderColor: '#FCA5A5',
  },
  {
    id: '2',
    type: '102',
    title: '102 Polis',
    status: 'Yardım Göstərildi',
    statusType: 'green',
    date: '15 İyun 2026, 23:40',
    address: 'Bakı, Fəvvarələr Meydanı',
    mapLink: true,
    attachments: [
      { type: 'video', label: '10s Video Yazısı Arxivləndi', icon: 'video-outline', color: '#059669' },
    ],
    bgColor: '#EEF2FF',
    borderColor: '#C7D2FE',
  },
  {
    id: '3',
    type: '112',
    title: '112 FHN / Yanğın',
    status: 'Briqada Yoldadır',
    statusType: 'orange',
    date: '10 İyun 2026, 15:45',
    address: 'Bakı, Atatürk prospekti 12',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
  },
  {
    id: '4',
    type: 'SOS',
    title: 'Ailə SOS (Yaxınlarıma Bildir)',
    status: 'Ləğv Edildi (Səhvən Basılma)',
    statusType: 'gray',
    date: '02 İyun 2026, 09:12',
    address: 'Bakı, Üzeyir Hacıbəyov küç., 34',
    bgColor: '#F5F3FF',
    borderColor: '#DDD6FE',
  },
];

export let DETAILED_EVENTS_STORE = {
  '1': {
    id: '1',
    type: '103',
    title: '103 Təcili Tibbi Yardım',
    status: 'Briqada Yoldadır',
    statusColor: '#E11D48',
    bgColor: '#FFF1F1',
    borderColor: '#FCA5A5',
    date: '30 İyun 2026',
    time: '11:15',
    address: 'Bakı, Nizami küçəsi 45',
    coords: '40.3783° N, 49.8524° E',
    timeline: [
      { title: 'Çağırış qəbul edildi', desc: 'Sistem çağırışı təsdiqlədi', time: '11:15', active: true },
      { title: 'Operator təsdiqi', desc: 'ITS tərəfindən operator təyin olundu', time: '11:16', active: true },
      { title: 'Briqada yola düşdü', desc: '103 Təcili Yardım ambulansı çıxdı', time: '11:18', active: true },
      { title: 'Ünvana çatma', desc: 'Briqadanın yaxınlaşma müddəti: 4 dəq.', time: 'Gözlənilir', active: false },
    ],
    audioFile: { duration: '0:15', label: 'Hadisə anı səs yazısı' },
    photoFile: { label: 'Hadisə anı fotoşəkili' },
  },
  '2': {
    id: '2',
    type: '102',
    title: '102 Polis / Asayiş',
    status: 'Yardım Göstərildi',
    statusColor: '#102E73',
    bgColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    date: '15 İyun 2026',
    time: '23:40',
    address: 'Bakı, Fəvvarələr Meydanı',
    coords: '40.3701° N, 49.8372° E',
    timeline: [
      { title: 'Çağırış qəbul edildi', desc: 'Təhlükəsizlik mərkəzi qeydə aldı', time: '23:40', active: true },
      { title: 'Polis patrul yönləndirildi', desc: 'Ərazi üzrə ən yaxın ekipaj yola çıxdı', time: '23:42', active: true },
      { title: 'Hadisə yerinə çatma', desc: 'Ekipaj ünvana yaxınlaşdı', time: '23:46', active: true },
      { title: 'Problem həll olundu', desc: 'İnsident aradan qaldırıldı, kömək edildi', time: '23:55', active: true },
    ],
    videoFile: { duration: '0:10', label: 'Hadisə anı video qeydi' },
  },
  '3': {
    id: '3',
    type: '112',
    title: '112 FHN / Yanğın',
    status: 'Briqada Yoldadır',
    statusColor: '#B45309',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    date: '10 İyun 2026',
    time: '15:45',
    address: 'Bakı, Atatürk prospekti 12',
    coords: '40.4093° N, 49.8681° E',
    timeline: [
      { title: 'Çağırış qəbul edildi', desc: 'FHN böhran idarəetmə mərkəzi', time: '15:45', active: true },
      { title: 'Briqada yola düşdü', desc: 'Yanğınsöndürmə briqadası çıxış etdi', time: '15:47', active: true },
    ],
  },
  '4': {
    id: '4',
    type: 'SOS',
    title: 'Ailə SOS',
    status: 'Ləğv Edildi (Səhvən Basılma)',
    statusColor: '#4B5563',
    bgColor: '#F5F3FF',
    borderColor: '#DDD6FE',
    date: '02 İyun 2026',
    time: '09:12',
    address: 'Bakı, Üzeyir Hacıbəyov küç., 34',
    coords: '40.3758° N, 49.8550° E',
    timeline: [
      { title: 'SOS siqnalı aktivləşdirildi', desc: 'Yaxın kontaktlara mövqe göndərildi', time: '09:12', active: true },
      { title: 'Çağırış ləğv edildi', desc: 'İstifadəçi tərəfindən səhvən basıldı və ləğv edildi', time: '09:13', active: true },
    ],
  },
};

export const addEvent = (event) => {
  EVENTS_STORE = [event, ...EVENTS_STORE];
  
  // Format detailed representation
  DETAILED_EVENTS_STORE[event.id] = {
    id: event.id,
    type: event.type,
    title: event.title,
    status: event.status,
    statusColor: event.type === '103' ? '#E11D48' : event.type === '102' ? '#102E73' : event.type === '112' ? '#B45309' : '#4B5563',
    bgColor: event.bgColor,
    borderColor: event.borderColor,
    date: '30 İyun 2026',
    time: '17:30',
    address: event.address,
    coords: '40.3758° N, 49.8550° E',
    timeline: [
      { title: 'Çağırış göndərildi', desc: 'Analiz əsasında avtomatik yönləndirmə edildı', time: '17:30', active: true },
      { title: 'Sistem qəbulu', desc: 'Müvafiq dövlət orqanı (ITS/FHN/DİN) bildiriş aldı', time: '17:31', active: true },
      { title: 'Briqada təyinatı', desc: 'Ərazi üzrə briqada təyin edilir', time: 'Gözlənilir', active: false }
    ],
    photoFile: event.attachments.find(a => a.type === 'image') ? { label: 'Hadisə anı fotoşəkili', uri: event.attachments.find(a => a.type === 'image').uri } : null,
    videoFile: event.attachments.find(a => a.type === 'video') ? { label: 'Hadisə anı video qeydi', uri: event.attachments.find(a => a.type === 'video').uri } : null,
  };
};
